export const skillsHobbies: string[] = [
    "Angular is literally my coding love language 👑",
    "Full-stack app queen—structure? I serve it, front *and* back.",
    "API wrangling like a digital cowboy 🤠 yeehaw",
    "Git + GitHub? Please. I commit like a champ.",
    "Vercel is basically my playground at this point.",
    "Debugging under pressure? I'm a licensed coding therapist, babe.",
    "I design in pastels and cozy-core vibes—soft, playful, *click me* energy.",
    "Wireframes? Yeah, I make those look like art school final projects.",
    "If it's not ✨clean✨ and polished, I'm not done yet.",
    "Digital routines, Notion dashboards, shortcut magic—I'm Type A but adorable.",
    "To-do lists? Slayed. Dishwashers? Feared me.",
    "I troubleshoot tech bugs, printer tantrums, and my own schedule—no notes.",
    "Designed my entire life around spoonie-friendly energy workarounds 🥄",
    "Coral Island royalty—Scott is mine, the ocean is home.",
    "The Sims, Little Kitty Big City, RimWorld, Detroit: Become Human—gimme cozy, immersive, and a lil ✨spice✨",
    "I crochet like a WiFi-enabled cottagecore grandma.",
    "I write fantasy that's immersive and *accidentally ASMR*.",
    "Baking bread is my emotional support activity.",
    "My car? A kawaii fortress on wheels.",
    "Milo's vibe is the blueprint. He *is* the moment.",
    "Pink and pastel everything—even when the base is brown. (We don't judge her 💀)",
    "I watch my bird cam with my *entire soul*.",
    "Journaling = daily love letters to future me.",
    "Gentle rhythms and chill quests keep me grounded and glowing 💫"
];
