export default function handler(req, res) {
    const bunnyFacts = [
        "A rabbit's teeth never stop growing!",
        "Bunnies do a happy jump called a 'binky.'",
        "Rabbits can rotate their ears 270 degrees.",
        "A group of bunnies is called a fluffle.",
        "Bunnies purr by grinding their teeth softly.",
        "A bunny’s favorite snack might be a slice of banana — but only in moderation!",
        "A bunny’s nose can twitch up to 150 times per minute.",
        "A group of bunnies is called a 'fluffle' in Canada.",
        "A rabbit's teeth never stop growing.",
        "A rabbit’s vision covers almost 360 degrees.",
        "A relaxed bunny might sprawl out with its legs behind it — this is called a ‘loaf’ or ‘sploot’.",
        "Baby bunnies are called kits or kittens.",
        "Bun says: 'A bunny’s favorite snack might be a slice of banana — but only in moderation!'",
        "Bun says: 'A bunny’s nose can twitch up to 150 times per minute.'",
        "Bun says: 'A group of bunnies is called a 'fluffle' in Canada.'",
        "Bun says: 'A rabbit’s vision covers almost 360 degrees.'",
        "Bun says: 'Bunnies are most active at dawn and dusk (crepuscular).'",
        "Bun says: 'Bunnies clean themselves like cats — they’re very tidy!'",
        "Bun says: 'Bunnies express happiness by doing a jump twist called a 'binky'.'",
        "Bun says: 'Bunnies have a blind spot right in front of their nose.'",
        "Bun says: 'Bunnies love cardboard boxes — they make great chew toys and hideouts.'",
        "Bun says: 'Bunnies need lots of hay to keep their digestive system healthy.'",
        "Bun says: 'Bunnies sometimes 'chatter' their teeth softly when content.'",
        "Bun says: 'Bunnies sometimes flop onto their side when extremely relaxed.'",
        "Bun says: 'Domestic rabbits can live 8-12 years with proper care.'",
        "Bun says: 'Male rabbits are called bucks; females are does.'",
        "Bun says: 'Not all rabbits like being held, but most love gentle petting.'",
        "Bun says: 'Rabbits can jump up to three feet high in a single leap.'",
        "Bun says: 'Rabbits can rotate their ears 270 degrees.'",
        "Bun says: 'Rabbits can see behind them without turning their heads.'",
        "Bun says: 'Rabbits chew over 120 times per minute.'",
        "Bun says: 'Rabbits communicate using body language, like thumping their hind legs.'",
        "Bun says: 'Rabbits’ back legs are extremely powerful — perfect for fast getaways.'",
        "Bun says: 'Rabbits’ ears help regulate their body temperature.'",
        "Bun says: 'Rabbits’ nails grow constantly and need regular trimming.'",
        "Bun says: 'Some bunnies will follow their humans around like puppies.'",
        "Bun says: 'Some rabbits enjoy listening to music.'",
        "Bun says: 'Some rabbits enjoy watching TV or YouTube with their humans.'",
        "Bunnies are most active at dawn and dusk (crepuscular).",
        "Bunnies can be litter-trained like cats.",
        "Bunnies clean themselves like cats — they’re very tidy!",
        "Bunnies express happiness by doing a jump twist called a 'binky'.",
        "Bunnies have 28 teeth.",
        "Bunnies have a blind spot right in front of their nose.",
        "Bunnies love cardboard boxes — they make great chew toys and hideouts.",
        "Bunnies need lots of hay to keep their digestive system healthy.",
        "Bunnies often have a 'zoomie hour' where they run around full speed.",
        "Bunnies often sleep with their eyes half-open — it’s a defense mechanism.",
        "Bunnies sleep with their eyes open.",
        "Bunnies sometimes 'chatter' their teeth softly when content.",
        "Bunnies sometimes flop onto their side when extremely relaxed.",
        "Bunny trivia: A bunny’s favorite snack might be a slice of banana — but only in moderation!",
        "Bunny trivia: A rabbit's teeth never stop growing.",
        "Bunny trivia: A relaxed bunny might sprawl out with its legs behind it — this is called a ‘loaf’ or ‘sploot’.",
        "Bunny trivia: Bunnies are most active at dawn and dusk (crepuscular).",
        "Bunny trivia: Bunnies can be litter-trained like cats.",
        "Bunny trivia: Bunnies clean themselves like cats — they’re very tidy!",
        "Bunny trivia: Bunnies express happiness by doing a jump twist called a 'binky'.",
        "Bunny trivia: Bunnies have a blind spot right in front of their nose.",
        "Bunny trivia: Bunnies need lots of hay to keep their digestive system healthy.",
        "Bunny trivia: Bunnies often have a 'zoomie hour' where they run around full speed.",
        "Bunny trivia: Bunnies often sleep with their eyes half-open — it’s a defense mechanism.",
        "Bunny trivia: Bunnies sleep with their eyes open.",
        "Bunny trivia: Each rabbit has a unique personality — some are cuddly, some are sassy!",
        "Bunny trivia: Lop-eared rabbits have ears that can drag on the ground.",
        "Bunny trivia: Male rabbits are called bucks; females are does.",
        "Bunny trivia: Not all rabbits like being held, but most love gentle petting.",
        "Bunny trivia: Rabbits can rotate their ears 270 degrees.",
        "Bunny trivia: Rabbits can see behind them without turning their heads.",
        "Bunny trivia: Rabbits can't vomit.",
        "Bunny trivia: Rabbits purr by gently grinding their teeth.",
        "Bunny trivia: Rabbits’ back legs are extremely powerful — perfect for fast getaways.",
        "Bunny trivia: Some bunnies will follow their humans around like puppies.",
        "Bunny trivia: Some rabbits enjoy listening to music.",
        "Bunny trivia: Some rabbits enjoy watching TV or YouTube with their humans.",
        "Bunny trivia: Wild rabbits live in complex tunnel systems called warrens.",
        "Cozy thought: A bunny’s favorite snack might be a slice of banana — but only in moderation!",
        "Cozy thought: A bunny’s nose can twitch up to 150 times per minute.",
        "Cozy thought: A group of bunnies is called a 'fluffle' in Canada.",
        "Cozy thought: A rabbit's teeth never stop growing.",
        "Cozy thought: A relaxed bunny might sprawl out with its legs behind it — this is called a ‘loaf’ or ‘sploot’.",
        "Cozy thought: Bunnies are most active at dawn and dusk (crepuscular).",
        "Cozy thought: Bunnies express happiness by doing a jump twist called a 'binky'.",
        "Cozy thought: Bunnies have 28 teeth.",
        "Cozy thought: Bunnies have a blind spot right in front of their nose.",
        "Cozy thought: Bunnies love cardboard boxes — they make great chew toys and hideouts.",
        "Cozy thought: Bunnies need lots of hay to keep their digestive system healthy.",
        "Cozy thought: Bunnies often have a 'zoomie hour' where they run around full speed.",
        "Cozy thought: Bunnies sleep with their eyes open.",
        "Cozy thought: Bunnies sometimes 'chatter' their teeth softly when content.",
        "Cozy thought: Bunnies sometimes flop onto their side when extremely relaxed.",
        "Cozy thought: Each rabbit has a unique personality — some are cuddly, some are sassy!",
        "Cozy thought: Lop-eared rabbits have ears that can drag on the ground.",
        "Cozy thought: Male rabbits are called bucks; females are does.",
        "Cozy thought: Rabbits can jump up to three feet high in a single leap.",
        "Cozy thought: Rabbits can rotate their ears 270 degrees.",
        "Cozy thought: Rabbits can see behind them without turning their heads.",
        "Cozy thought: Rabbits can't vomit.",
        "Cozy thought: Rabbits chew over 120 times per minute.",
        "Cozy thought: Rabbits purr by gently grinding their teeth.",
        "Cozy thought: Rabbits wiggle their noses to smell better and express curiosity.",
        "Cozy thought: Rabbits’ nails grow constantly and need regular trimming.",
        "Cozy thought: Some bunnies will follow their humans around like puppies.",
        "Cozy thought: Some rabbits enjoy watching TV or YouTube with their humans.",
        "Cozy thought: Wild rabbits live in complex tunnel systems called warrens.",
        "Did you know? A group of bunnies is called a 'fluffle' in Canada.",
        "Did you know? A rabbit’s vision covers almost 360 degrees.",
        "Did you know? A relaxed bunny might sprawl out with its legs behind it — this is called a ‘loaf’ or ‘sploot’.",
        "Did you know? Baby bunnies are called kits or kittens.",
        "Did you know? Bunnies can be litter-trained like cats.",
        "Did you know? Bunnies clean themselves like cats — they’re very tidy!",
        "Did you know? Bunnies have 28 teeth.",
        "Did you know? Bunnies have a blind spot right in front of their nose.",
        "Did you know? Bunnies often have a 'zoomie hour' where they run around full speed.",
        "Did you know? Bunnies often sleep with their eyes half-open — it’s a defense mechanism.",
        "Did you know? Bunnies sleep with their eyes open.",
        "Did you know? Bunnies sometimes flop onto their side when extremely relaxed.",
        "Did you know? Each rabbit has a unique personality — some are cuddly, some are sassy!",
        "Did you know? Lop-eared rabbits have ears that can drag on the ground.",
        "Did you know? Male rabbits are called bucks; females are does.",
        "Did you know? Not all rabbits like being held, but most love gentle petting.",
        "Did you know? Rabbits can jump up to three feet high in a single leap.",
        "Did you know? Rabbits can rotate their ears 270 degrees.",
        "Did you know? Rabbits can see behind them without turning their heads.",
        "Did you know? Rabbits wiggle their noses to smell better and express curiosity.",
        "Did you know? Rabbits’ back legs are extremely powerful — perfect for fast getaways.",
        "Did you know? Rabbits’ nails grow constantly and need regular trimming.",
        "Did you know? Some rabbits enjoy watching TV or YouTube with their humans.",
        "Did you know? Wild rabbits live in complex tunnel systems called warrens.",
        "Domestic rabbits can live 8-12 years with proper care.",
        "Each rabbit has a unique personality — some are cuddly, some are sassy!",
        "Fluffy truth: A bunny’s favorite snack might be a slice of banana — but only in moderation!",
        "Fluffy truth: A group of bunnies is called a 'fluffle' in Canada.",
        "Fluffy truth: A rabbit’s vision covers almost 360 degrees.",
        "Fluffy truth: A relaxed bunny might sprawl out with its legs behind it — this is called a ‘loaf’ or ‘sploot’.",
        "Fluffy truth: Baby bunnies are called kits or kittens.",
        "Fluffy truth: Bunnies clean themselves like cats — they’re very tidy!",
        "Fluffy truth: Bunnies have 28 teeth.",
        "Fluffy truth: Bunnies have a blind spot right in front of their nose.",
        "Fluffy truth: Bunnies need lots of hay to keep their digestive system healthy.",
        "Fluffy truth: Bunnies often have a 'zoomie hour' where they run around full speed.",
        "Fluffy truth: Bunnies often sleep with their eyes half-open — it’s a defense mechanism.",
        "Fluffy truth: Bunnies sleep with their eyes open.",
        "Fluffy truth: Bunnies sometimes 'chatter' their teeth softly when content.",
        "Fluffy truth: Bunnies sometimes flop onto their side when extremely relaxed.",
        "Fluffy truth: Domestic rabbits can live 8-12 years with proper care.",
        "Fluffy truth: Each rabbit has a unique personality — some are cuddly, some are sassy!",
        "Fluffy truth: Lop-eared rabbits have ears that can drag on the ground.",
        "Fluffy truth: Male rabbits are called bucks; females are does.",
        "Fluffy truth: Not all rabbits like being held, but most love gentle petting.",
        "Fluffy truth: Rabbits can jump up to three feet high in a single leap.",
        "Fluffy truth: Rabbits can rotate their ears 270 degrees.",
        "Fluffy truth: Rabbits can see behind them without turning their heads.",
        "Fluffy truth: Rabbits can't vomit.",
        "Fluffy truth: Rabbits chew over 120 times per minute.",
        "Fluffy truth: Rabbits communicate using body language, like thumping their hind legs.",
        "Fluffy truth: Rabbits wiggle their noses to smell better and express curiosity.",
        "Fluffy truth: Rabbits’ back legs are extremely powerful — perfect for fast getaways.",
        "Fluffy truth: Rabbits’ ears help regulate their body temperature.",
        "Fluffy truth: Rabbits’ nails grow constantly and need regular trimming.",
        "Fluffy truth: Some bunnies will follow their humans around like puppies.",
        "Fluffy truth: Some rabbits enjoy listening to music.",
        "Fluffy truth: Some rabbits enjoy watching TV or YouTube with their humans.",
        "Fluffy truth: Wild rabbits live in complex tunnel systems called warrens.",
        "From the warren: A bunny’s favorite snack might be a slice of banana — but only in moderation!",
        "From the warren: A rabbit’s vision covers almost 360 degrees.",
        "From the warren: A relaxed bunny might sprawl out with its legs behind it — this is called a ‘loaf’ or ‘sploot’.",
        "From the warren: Bunnies are most active at dawn and dusk (crepuscular).",
        "From the warren: Bunnies can be litter-trained like cats.",
        "From the warren: Bunnies clean themselves like cats — they’re very tidy!",
        "From the warren: Bunnies express happiness by doing a jump twist called a 'binky'.",
        "From the warren: Bunnies have 28 teeth.",
        "From the warren: Bunnies have a blind spot right in front of their nose.",
        "From the warren: Bunnies love cardboard boxes — they make great chew toys and hideouts.",
        "From the warren: Bunnies often sleep with their eyes half-open — it’s a defense mechanism.",
        "From the warren: Lop-eared rabbits have ears that can drag on the ground.",
        "From the warren: Male rabbits are called bucks; females are does.",
        "From the warren: Rabbits can jump up to three feet high in a single leap.",
        "From the warren: Rabbits can't vomit.",
        "From the warren: Rabbits chew over 120 times per minute.",
        "From the warren: Rabbits communicate using body language, like thumping their hind legs.",
        "From the warren: Rabbits purr by gently grinding their teeth.",
        "From the warren: Rabbits’ back legs are extremely powerful — perfect for fast getaways.",
        "From the warren: Some rabbits enjoy listening to music.",
        "From the warren: Wild rabbits live in complex tunnel systems called warrens.",
        "Fun fact: A bunny’s favorite snack might be a slice of banana — but only in moderation!",
        "Fun fact: A bunny’s nose can twitch up to 150 times per minute.",
        "Fun fact: A group of bunnies is called a 'fluffle' in Canada.",
        "Fun fact: A rabbit's teeth never stop growing.",
        "Fun fact: A relaxed bunny might sprawl out with its legs behind it — this is called a ‘loaf’ or ‘sploot’.",
        "Fun fact: Bunnies can be litter-trained like cats.",
        "Fun fact: Bunnies clean themselves like cats — they’re very tidy!",
        "Fun fact: Bunnies express happiness by doing a jump twist called a 'binky'.",
        "Fun fact: Bunnies have 28 teeth.",
        "Fun fact: Bunnies often have a 'zoomie hour' where they run around full speed.",
        "Fun fact: Bunnies sleep with their eyes open.",
        "Fun fact: Bunnies sometimes 'chatter' their teeth softly when content.",
        "Fun fact: Bunnies sometimes flop onto their side when extremely relaxed.",
        "Fun fact: Each rabbit has a unique personality — some are cuddly, some are sassy!",
        "Fun fact: Male rabbits are called bucks; females are does.",
        "Fun fact: Not all rabbits like being held, but most love gentle petting.",
        "Fun fact: Rabbits can rotate their ears 270 degrees.",
        "Fun fact: Rabbits can't vomit.",
        "Fun fact: Rabbits communicate using body language, like thumping their hind legs.",
        "Fun fact: Rabbits purr by gently grinding their teeth.",
        "Fun fact: Rabbits wiggle their noses to smell better and express curiosity.",
        "Fun fact: Rabbits’ back legs are extremely powerful — perfect for fast getaways.",
        "Fun fact: Rabbits’ nails grow constantly and need regular trimming.",
        "Fun fact: Some bunnies will follow their humans around like puppies.",
        "Fun fact: Some rabbits enjoy watching TV or YouTube with their humans.",
        "Here's something cute — a group of bunnies is called a 'fluffle' in canada.",
        "Here's something cute — a rabbit's teeth never stop growing.",
        "Here's something cute — a rabbit’s vision covers almost 360 degrees.",
        "Here's something cute — baby bunnies are called kits or kittens.",
        "Here's something cute — bunnies can be litter-trained like cats.",
        "Here's something cute — bunnies clean themselves like cats — they’re very tidy!",
        "Here's something cute — bunnies express happiness by doing a jump twist called a 'binky'.",
        "Here's something cute — bunnies have a blind spot right in front of their nose.",
        "Here's something cute — bunnies love cardboard boxes — they make great chew toys and hideouts.",
        "Here's something cute — bunnies need lots of hay to keep their digestive system healthy.",
        "Here's something cute — bunnies often have a 'zoomie hour' where they run around full speed.",
        "Here's something cute — bunnies often sleep with their eyes half-open — it’s a defense mechanism.",
        "Here's something cute — bunnies sleep with their eyes open.",
        "Here's something cute — bunnies sometimes 'chatter' their teeth softly when content.",
        "Here's something cute — bunnies sometimes flop onto their side when extremely relaxed.",
        "Here's something cute — domestic rabbits can live 8-12 years with proper care.",
        "Here's something cute — lop-eared rabbits have ears that can drag on the ground.",
        "Here's something cute — male rabbits are called bucks; females are does.",
        "Here's something cute — rabbits can jump up to three feet high in a single leap.",
        "Here's something cute — rabbits can rotate their ears 270 degrees.",
        "Here's something cute — rabbits can see behind them without turning their heads.",
        "Here's something cute — rabbits can't vomit.",
        "Here's something cute — rabbits chew over 120 times per minute.",
        "Here's something cute — rabbits communicate using body language, like thumping their hind legs.",
        "Here's something cute — rabbits purr by gently grinding their teeth.",
        "Here's something cute — rabbits’ back legs are extremely powerful — perfect for fast getaways.",
        "Here's something cute — rabbits’ nails grow constantly and need regular trimming.",
        "Here's something cute — some bunnies will follow their humans around like puppies.",
        "Here's something cute — some rabbits enjoy listening to music.",
        "Here's something cute — some rabbits enjoy watching tv or youtube with their humans.",
        "Here's something cute — wild rabbits live in complex tunnel systems called warrens.",
        "Little known bunny fact: A bunny’s favorite snack might be a slice of banana — but only in moderation!",
        "Little known bunny fact: A rabbit's teeth never stop growing.",
        "Little known bunny fact: Bunnies are most active at dawn and dusk (crepuscular).",
        "Little known bunny fact: Bunnies can be litter-trained like cats.",
        "Little known bunny fact: Bunnies clean themselves like cats — they’re very tidy!",
        "Little known bunny fact: Bunnies express happiness by doing a jump twist called a 'binky'.",
        "Little known bunny fact: Bunnies need lots of hay to keep their digestive system healthy.",
        "Little known bunny fact: Bunnies often have a 'zoomie hour' where they run around full speed.",
        "Little known bunny fact: Bunnies sleep with their eyes open.",
        "Little known bunny fact: Bunnies sometimes flop onto their side when extremely relaxed.",
        "Little known bunny fact: Domestic rabbits can live 8-12 years with proper care.",
        "Little known bunny fact: Lop-eared rabbits have ears that can drag on the ground.",
        "Little known bunny fact: Male rabbits are called bucks; females are does.",
        "Little known bunny fact: Rabbits can rotate their ears 270 degrees.",
        "Little known bunny fact: Rabbits can see behind them without turning their heads.",
        "Little known bunny fact: Rabbits chew over 120 times per minute.",
        "Little known bunny fact: Rabbits wiggle their noses to smell better and express curiosity.",
        "Little known bunny fact: Rabbits’ back legs are extremely powerful — perfect for fast getaways.",
        "Little known bunny fact: Rabbits’ ears help regulate their body temperature.",
        "Little known bunny fact: Some bunnies will follow their humans around like puppies.",
        "Little known bunny fact: Wild rabbits live in complex tunnel systems called warrens.",
        "Lop-eared rabbits have ears that can drag on the ground.",
        "Male rabbits are called bucks; females are does.",
        "Not all rabbits like being held, but most love gentle petting.",
        "Rabbits can jump up to three feet high in a single leap.",
        "Rabbits can rotate their ears 270 degrees.",
        "Rabbits can see behind them without turning their heads.",
        "Rabbits can't vomit.",
        "Rabbits chew over 120 times per minute.",
        "Rabbits communicate using body language, like thumping their hind legs.",
        "Rabbits purr by gently grinding their teeth.",
        "Rabbits wiggle their noses to smell better and express curiosity.",
        "Rabbits’ back legs are extremely powerful — perfect for fast getaways.",
        "Rabbits’ ears help regulate their body temperature.",
        "Rabbits’ nails grow constantly and need regular trimming.",
        "Some bunnies will follow their humans around like puppies.",
        "Some rabbits enjoy listening to music.",
        "Some rabbits enjoy watching TV or YouTube with their humans.",
        "Wild rabbits live in complex tunnel systems called warrens.",
        "🐰 A rabbit's teeth never stop growing.",
        "🐰 A rabbit’s vision covers almost 360 degrees.",
        "🐰 A relaxed bunny might sprawl out with its legs behind it — this is called a ‘loaf’ or ‘sploot’.",
        "🐰 Baby bunnies are called kits or kittens.",
        "🐰 Bunnies are most active at dawn and dusk (crepuscular).",
        "🐰 Bunnies can be litter-trained like cats.",
        "🐰 Bunnies clean themselves like cats — they’re very tidy!",
        "🐰 Bunnies express happiness by doing a jump twist called a 'binky'.",
        "🐰 Bunnies have 28 teeth.",
        "🐰 Bunnies have a blind spot right in front of their nose.",
        "🐰 Bunnies need lots of hay to keep their digestive system healthy.",
        "🐰 Bunnies often sleep with their eyes half-open — it’s a defense mechanism.",
        "🐰 Bunnies sleep with their eyes open.",
        "🐰 Bunnies sometimes 'chatter' their teeth softly when content.",
        "🐰 Domestic rabbits can live 8-12 years with proper care.",
        "🐰 Male rabbits are called bucks; females are does.",
        "🐰 Not all rabbits like being held, but most love gentle petting.",
        "🐰 Rabbits can jump up to three feet high in a single leap.",
        "🐰 Rabbits can't vomit.",
        "🐰 Rabbits purr by gently grinding their teeth.",
        "🐰 Rabbits wiggle their noses to smell better and express curiosity.",
        "🐰 Rabbits’ back legs are extremely powerful — perfect for fast getaways.",
        "🐰 Rabbits’ ears help regulate their body temperature.",
        "🐰 Some bunnies will follow their humans around like puppies.",
        "🐰 Some rabbits enjoy listening to music.",
    ];

    const fact = bunnyFacts[Math.floor(Math.random() * bunnyFacts.length)];
    res.status(200).json({ fact });
}
